In [15]:
import numpy as np

In [16]:
l = [1,2,3,4]

In [17]:
a = np.array(l)

In [18]:
a[1:]

array([2, 3, 4])

In [19]:
l2 = [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]

In [20]:
a2= np.array(l2)

In [21]:
a2[2:4,1:3]

array([[3, 3],
       [4, 4]])

In [22]:
a2[:,0]

array([1, 2, 3, 4])

In [23]:
# for 3-d array we are using an image
import cv2

In [31]:
photo = cv2.imread('mountains.jpg')

In [25]:
photo.shape

(400, 600, 3)

In [26]:
photo[:,:,:]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [204, 193, 189],
        [203, 192, 188],
        [202, 191, 187]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [203, 192, 188],
        [203, 192, 188],
        [202, 191, 187]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [203, 192, 188],
        [202, 191, 187],
        [202, 191, 187]],

       ...,

       [[133, 122, 102],
        [133, 122, 102],
        [134, 123, 103],
        ...,
        [ 12,  22,  22],
        [  8,  22,  21],
        [  7,  23,  22]],

       [[134, 123, 103],
        [135, 124, 104],
        [135, 124, 104],
        ...,
        [ 14,  19,  20],
        [ 10,  20,  20],
        [  0,  10,  10]],

       [[136, 125, 105],
        [136, 125, 105],
        [137, 126, 106],
        ...,
        [ 37,  41,  42],
        [ 34,  42,  42],
        [ 12,  22,  22]]

In [27]:
photo[:,:,0]

array([[255, 255, 255, ..., 204, 203, 202],
       [255, 255, 255, ..., 203, 203, 202],
       [255, 255, 255, ..., 203, 202, 202],
       ...,
       [133, 133, 134, ...,  12,   8,   7],
       [134, 135, 135, ...,  14,  10,   0],
       [136, 136, 137, ...,  37,  34,  12]], dtype=uint8)

In [28]:
cv2.imshow('hi',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
#to remove red color
photo[:,:,2] = 0

In [30]:
cv2.imshow('hi',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
# to split photo according to 3 diferent colors
b,g,r = cv2.split(photo)

In [33]:
# to combine all 3 different colors
cv2.merge([b,g,r])

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [204, 193, 189],
        [203, 192, 188],
        [202, 191, 187]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [203, 192, 188],
        [203, 192, 188],
        [202, 191, 187]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [203, 192, 188],
        [202, 191, 187],
        [202, 191, 187]],

       ...,

       [[133, 122, 102],
        [133, 122, 102],
        [134, 123, 103],
        ...,
        [ 12,  22,  22],
        [  8,  22,  21],
        [  7,  23,  22]],

       [[134, 123, 103],
        [135, 124, 104],
        [135, 124, 104],
        ...,
        [ 14,  19,  20],
        [ 10,  20,  20],
        [  0,  10,  10]],

       [[136, 125, 105],
        [136, 125, 105],
        [137, 126, 106],
        ...,
        [ 37,  41,  42],
        [ 34,  42,  42],
        [ 12,  22,  22]]

In [34]:
r.shape

(400, 600)

In [46]:
z = np.zeros((400,600))

In [47]:
z.shape

(400, 600)

In [48]:
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [49]:
# one more way to remove red color

cv2.merge([b,g,z])

error: C:\ci\opencv_1512688052760\work\modules\core\src\convert.cpp:336: error: (-215) mv[i].size == mv[0].size && mv[i].depth() == depth in function cv::merge


In [51]:
r.dtype

dtype('uint8')

In [52]:
z.dtype

dtype('float64')

In [53]:
# to convert in 'uint8'

z = z.astype('uint8')

In [54]:
# one more way to remove red color

cv2.merge([b,g,z])

array([[[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [204, 193,   0],
        [203, 192,   0],
        [202, 191,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [203, 192,   0],
        [203, 192,   0],
        [202, 191,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [203, 192,   0],
        [202, 191,   0],
        [202, 191,   0]],

       ...,

       [[133, 122,   0],
        [133, 122,   0],
        [134, 123,   0],
        ...,
        [ 12,  22,   0],
        [  8,  22,   0],
        [  7,  23,   0]],

       [[134, 123,   0],
        [135, 124,   0],
        [135, 124,   0],
        ...,
        [ 14,  19,   0],
        [ 10,  20,   0],
        [  0,  10,   0]],

       [[136, 125,   0],
        [136, 125,   0],
        [137, 126,   0],
        ...,
        [ 37,  41,   0],
        [ 34,  42,   0],
        [ 12,  22,   0]]