In [1]:
# tf == numpy
import tensorflow  as tf

In [2]:
a = tf.constant(5)

In [26]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [27]:
tf.__version__

'2.1.0'

In [4]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [5]:
import numpy as np

In [7]:
b= np.array(["sdghf","hi","hi"])

In [8]:
type(b)

numpy.ndarray

In [9]:
b

array(['sdghf', 'hi', 'hi'], dtype='<U5')

In [10]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [11]:
a.numpy()

5

In [12]:
a.assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [13]:
b = tf.Variable(10)

In [14]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [15]:
b.numpy()

10

In [16]:
b.assign(15)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=15>

In [17]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=15>

In [18]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [19]:
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=15>

In [20]:
c = a + b 

In [21]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [22]:
a = tf.constant(5)
b = tf.constant(6)

In [24]:
# eager execution
def lw(a,b):
    c = a*b+1
    d = a*b*3
    print(c)
    print(d)

In [25]:
lw(a,b)

tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)


In [28]:
# lazy execution

@tf.function
def lw(a,b):
    c = a*b+1
    d = a*b*3
    print(c)
    print(d)

In [29]:
lw(a,b)

Tensor("add:0", shape=(), dtype=int32)
Tensor("mul_2:0", shape=(), dtype=int32)


In [66]:
x=tf.constant(3.0)
y=tf.constant(6.0)

In [67]:
w= tf.Variable(20.0)

In [68]:
def losscomputation():
    with tf.GradientTape() as tape:
        loss = tf.math.abs(w*x -y)
    dx = tape.gradient(loss, w)
    print('w: ' , w.numpy(), ' loss: ', loss.numpy(), 'dx :' , dx.numpy())
    w.assign(w-dx)

In [69]:
i=0

In [70]:
while i<=10:
    losscompute()
    i+=1

weight :  20.0 loss :  54.0
weight :  17.0 loss :  45.0
weight :  14.0 loss :  36.0
weight :  11.0 loss :  27.0
weight :  8.0 loss :  18.0
weight :  5.0 loss :  9.0
weight :  2.0 loss :  0.0
weight :  2.0 loss :  0.0
weight :  2.0 loss :  0.0
weight :  2.0 loss :  0.0
weight :  2.0 loss :  0.0


In [42]:
dx

In [9]:
import tensorflow as tf

In [17]:
x =tf.constant(3.0)

In [27]:
y = tf.constant(6.0)

In [28]:
x =tf.constant(4.0)

In [31]:
y = tf.constant(8.0)

In [32]:
x =tf.constant(5.0)

In [33]:
y = tf.constant(15.0)

In [19]:
w = tf.Variable(20.0)

In [38]:
# back propogation
with tf.GradientTape() as tape:
    # loss / cost function
    # feed forwarding 
    # neuron : w*x -y : linear activation function
    loss = tf.math.abs(w*x -y)
    # optimizer: descent, means change weight, goal to reach minimize error
    dx = tape.gradient(loss, w )
    # adjusting weight
    w.assign(w-dx)
    print("weight :" , w.numpy(), "descent : ", dx.numpy(), "loss :",  loss.numpy())
    
    

weight : 7.0 descent :  -5.0 loss : 5.0
